#!/bin/bash
# Run a command with every secret-like variable stripped. Never prints env values.
exec env -u DATABASE_URL -u OPENAI_API_KEY -u ANTHROPIC_API_KEY -u XAI_API_KEY \
  -u ENGINE_OPENAI_KEY -u ENGINE_ANTHROPIC_KEY -u ENGINE_XAI_KEY \
  -u ALPACA_API_KEY_ID -u ALPACA_API_SECRET_KEY -u AWS_ACCESS_KEY_ID -u AWS_SECRET_ACCESS_KEY \
  -u ENGINE_DATABASE_URL -u WEB_DATABASE_URL -u GH_TOKEN -u GITHUB_TOKEN -u CLOUDSDK_AUTH_ACCESS_TOKEN -u CLAUDE_CODE_MESSAGING_TOKEN "$@"
